"""Added sensor values

Revision ID: 3d257bbc7096
Revises: 
Create Date: 2020-05-18 17:16:49.526780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d257bbc7096'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('humidity_temp', sa.Float(), nullable=True),
    sa.Column('baro_temp', sa.Float(), nullable=True),
    sa.Column('baro_pressure', sa.Float(), nullable=True),
    sa.Column('light', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_data')
    # ### end Alembic commands ###
