"""Tweaks

Revision ID: b9900a0f475d
Revises: 40562f975781
Create Date: 2020-05-22 20:02:25.542693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9900a0f475d'
down_revision = '40562f975781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_data', sa.Column('danger_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_data', 'danger_level')
    # ### end Alembic commands ###
