"""Added sensor values

Revision ID: d14b053e4dcf
Revises: 065e4a1c99fb
Create Date: 2020-05-18 15:19:35.716587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd14b053e4dcf'
down_revision = '065e4a1c99fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_data', sa.Column('baro_pressure', sa.Float(), nullable=True))
    op.add_column('sensor_data', sa.Column('baro_temp', sa.Float(), nullable=True))
    op.add_column('sensor_data', sa.Column('humidity', sa.Float(), nullable=True))
    op.add_column('sensor_data', sa.Column('ir_temp', sa.Float(), nullable=True))
    op.add_column('sensor_data', sa.Column('light', sa.Float(), nullable=True))
    op.drop_column('sensor_data', 'temperature')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_data', sa.Column('temperature', sa.INTEGER(), nullable=True))
    op.drop_column('sensor_data', 'light')
    op.drop_column('sensor_data', 'ir_temp')
    op.drop_column('sensor_data', 'humidity')
    op.drop_column('sensor_data', 'baro_temp')
    op.drop_column('sensor_data', 'baro_pressure')
    # ### end Alembic commands ###
